import type { Product } from '@/types';

/** A complete product document for shop tests (fields mirror the seed catalogue). */
export function makeShopProduct(overrides: Partial<Product> & Pick<Product, 'id'>): Product {
  const { id } = overrides;
  return {
    slug: id,
    name: id,
    description: '',
    make: 'Garage Originals',
    model: id,
    series: 'hw-turbo-2025',
    seriesName: 'HW Turbo',
    seriesNumber: 1,
    collectionNumber: 1,
    year: 2025,
    scale: '1:64',
    color: 'Black',
    material: 'Die-cast metal body, plastic base',
    vehicleType: 'Coupe',
    category: 'sports',
    rarity: 'common',
    rarityScore: 3,
    collectorScore: 5,
    themedStats: { topSpeedKmh: 300, powerHp: 500 },
    price: 249,
    compareAtPrice: null,
    currency: 'INR',
    stock: 50,
    limitedEdition: null,
    images: [],
    primaryImage: '/placeholders/car-generic.svg',
    ratingAvg: 0,
    ratingCount: 0,
    tags: [],
    isNew: false,
    isFeatured: false,
    isVault: false,
    isActive: true,
    createdAt: 1_760_000_000_000,
    updatedAt: 1_760_000_000_000,
    ...overrides,
  };
}

const DAY = 86_400_000;

/**
 * Ten cars covering every view, rarity, availability level and scale:
 * - new: revuelto, gt3, midnight · premium: revuelto (tag), amg-one (1:43), turbo-33 (1:18, ₹2,499), supra (₹1,199)
 * - limited: amg-one, turbo-33 (limited rarity + vault)
 * - sold out: supra, gr010 · low stock (≤10): revuelto (8), amg-one (5), turbo-33 (5)
 */
export const CATALOGUE: readonly Product[] = [
  makeShopProduct({
    id: 'lamborghini-revuelto',
    name: 'Lamborghini Revuelto',
    make: 'Lamborghini',
    model: 'Revuelto',
    series: 'hw-exotics-2026',
    seriesName: 'HW Exotics',
    year: 2026,
    color: 'Green',
    category: 'sports',
    rarity: 'super-rare',
    rarityScore: 9,
    collectorScore: 9,
    price: 1299,
    stock: 8,
    tags: ['exotic', 'premium'],
    isNew: true,
    ratingAvg: 4.2,
    ratingCount: 3,
    createdAt: 1_760_000_000_000 + 10 * DAY,
  }),
  makeShopProduct({
    id: 'porsche-911-gt3-rs',
    name: 'Porsche 911 GT3 RS',
    make: 'Porsche',
    model: '911 GT3 RS',
    series: 'hw-exotics-2026',
    seriesName: 'HW Exotics',
    year: 2026,
    color: 'Blue',
    category: 'sports',
    rarity: 'rare',
    rarityScore: 6,
    collectorScore: 8,
    price: 499,
    stock: 26,
    isNew: true,
    ratingAvg: 4.7,
    ratingCount: 6,
    createdAt: 1_760_000_000_000 + 9 * DAY,
  }),
  makeShopProduct({
    id: 'mercedes-amg-one',
    name: 'Mercedes-AMG ONE',
    make: 'Mercedes-AMG',
    model: 'ONE',
    series: 'hw-exotics-2026',
    seriesName: 'HW Exotics',
    year: 2026,
    scale: '1:43',
    color: 'Silver',
    category: 'limited',
    rarity: 'limited',
    rarityScore: 9,
    collectorScore: 10,
    price: 2199,
    stock: 5,
    isVault: true,
    createdAt: 1_760_000_000_000 + 8 * DAY,
  }),
  makeShopProduct({
    id: 'midnight-blower',
    name: 'Midnight Blower',
    make: 'Garage Originals',
    model: 'Midnight Blower',
    series: 'hw-legends-2026',
    seriesName: 'HW Legends',
    year: 2026,
    color: 'Purple',
    category: 'special',
    rarity: 'rare',
    rarityScore: 6,
    collectorScore: 7,
    price: 449,
    stock: 29,
    isNew: true,
    createdAt: 1_760_000_000_000 + 7 * DAY,
  }),
  makeShopProduct({
    id: 'porsche-911-turbo-3-3',
    name: 'Porsche 911 Turbo 3.3 (930)',
    make: 'Porsche',
    model: '911 Turbo 3.3 (930)',
    series: 'hw-legends-2026',
    seriesName: 'HW Legends',
    year: 2026,
    scale: '1:18',
    color: 'Black',
    category: 'limited',
    rarity: 'limited',
    rarityScore: 9,
    collectorScore: 10,
    price: 2499,
    stock: 5,
    isVault: true,
    createdAt: 1_760_000_000_000 + 6 * DAY,
  }),
  makeShopProduct({
    id: 'toyota-supra-a80',
    name: 'Toyota Supra (A80)',
    make: 'Toyota',
    model: 'Supra (A80)',
    color: 'Orange',
    category: 'sports',
    rarity: 'super-rare',
    rarityScore: 9,
    collectorScore: 9,
    price: 1199,
    stock: 0,
    ratingAvg: 4.8,
    ratingCount: 5,
    createdAt: 1_760_000_000_000 + 5 * DAY,
  }),
  makeShopProduct({
    id: 'porsche-911-turbo-s',
    name: 'Porsche 911 Turbo S',
    make: 'Porsche',
    model: '911 Turbo S',
    color: 'Red',
    category: 'sports',
    rarity: 'common',
    price: 349,
    stock: 64,
    createdAt: 1_760_000_000_000 + 4 * DAY,
  }),
  makeShopProduct({
    id: 'porsche-911-safari-rally',
    name: 'Porsche 911 Safari Rally',
    make: 'Porsche',
    model: '911 Safari Rally',
    series: 'hw-off-road-2024',
    seriesName: 'HW Off-Road',
    year: 2024,
    color: 'White',
    category: 'off-road',
    rarity: 'rare',
    rarityScore: 7,
    collectorScore: 8,
    price: 649,
    stock: 16,
    createdAt: 1_760_000_000_000 + 3 * DAY,
  }),
  makeShopProduct({
    id: 'toyota-gr010-hybrid',
    name: 'Toyota GR010 Hybrid',
    make: 'Toyota',
    model: 'GR010 Hybrid',
    series: 'hw-race-day-2024',
    seriesName: 'HW Race Day',
    year: 2024,
    color: 'Red',
    category: 'racing',
    rarity: 'rare',
    rarityScore: 6,
    collectorScore: 7,
    price: 649,
    stock: 0,
    createdAt: 1_760_000_000_000 + 2 * DAY,
  }),
  makeShopProduct({
    id: 'maruti-suzuki-swift-inrc-rally',
    name: 'Maruti Suzuki Swift INRC Rally',
    make: 'Maruti Suzuki',
    model: 'Swift INRC Rally',
    series: 'hw-race-day-2024',
    seriesName: 'HW Race Day',
    year: 2024,
    color: 'Blue',
    category: 'racing',
    rarity: 'common',
    rarityScore: 2,
    collectorScore: 6,
    price: 199,
    stock: 45,
    ratingAvg: 4,
    ratingCount: 2,
    createdAt: 1_760_000_000_000 + 1 * DAY,
  }),
];

export const ids = (products: readonly Product[]): string[] =>
  products.map((product) => product.id);
